kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: depdns-read-only-binding
  labels:
    app: k8s-deploy-external-dns
subjects:
- kind: ServiceAccount
  name: depdnssa
  namespace: default
roleRef:
  kind: ClusterRole
  name: depdns-read-only
  apiGroup: rbac.authorization.k8s.io
