apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  labels:
    app: k8s-deploy-secret
type: Opaque
stringData:
  ovh.ini: |-
    [default]
    endpoint=ovh-eu
    [ovh-eu]
    application_key=buuuuuuuu
    application_secret=baaaaaaaaaaaaSS
    consumer_key=Beeeeeeeeee
  k8s.key: |-
    <token>
    kubernetes
    <ssl_verify-False>